blank_issues_enabled: false
contact_links:
  - name: ğŸ“š æ–‡æ¡£
    url: https://github.com/xixu-me/Xget/blob/main/README.zh-Hans.md
    about: æŸ¥çœ‹å­˜å‚¨åº“çš„ README æ–‡æ¡£
  - name: ğŸ” URL è½¬æ¢å™¨
    url: https://xuc.xi-xu.me
    about: è®¿é—®é…å¥— web åº”ç”¨ç¨‹åº
  - name: ğŸ” å®‰å…¨æ¼æ´æŠ¥å‘Š
    url: https://github.com/xixu-me/xget/security/policy#-%E6%8A%A5%E5%91%8A%E5%AE%89%E5%85%A8%E6%BC%8F%E6%B4%9E
    about: æŠ¥å‘Šå®‰å…¨æ¼æ´
